mira:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controller 1 ---------------------------------------
    roll_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    # Position Controller 2 ---------------------------------------
    pitch_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: pitch_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    # Position Controller 3 ---------------------------------------
    yaw_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: yaw_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}