gurdy:
    # Publish all joint states
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # 1st leg
    1_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM1_yaw_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    1_2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM1_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    1_3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: upperleg_lowerleg_M1_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    # 2nd leg
    2_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM2_yaw_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    2_2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM2_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    2_3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: upperleg_lowerleg_M2_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    # 3rd leg
    3_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM3_yaw_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    3_2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM3_joint
      pid: {p: 1.0, i: 1.0, d: 0}

    3_3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: upperleg_lowerleg_M3_joint
      pid: {p: 1.0, i: 1.0, d: 0}